on: [push]

jobs:
  print-version:
    runs-on: ubuntu-latest
    name: A job to print the version
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: test action
        id: get-version
        uses: simpplr/package-json-version@main
        with:
          path: .
      - name: Print the version
        run: echo "The version was ${{ steps.get-version.outputs.version }}"
